---
title: Stat 541 Experimental Design Project 2
author: "Ben DeVries, Eric Folsom, Ryan Kardoes, Alex Trauner"
format: pdf
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(emmeans)
library(ggfortify)
theme_set(theme_bw())
```

# LEVEL 1 Header

## LEVEL 2 Header

### LEVEL 3 Header

#### LEVEL 4 Header

1. List Item 1
   1. Sublist item 1
      1. sub-sublist item 1
2. List Item 2
3. List Item 3

- Unordered list item
  - unordered sub-list item

# Part 1: Experimental Design Plan (9-step checklist)

1.	Define the objectives: 
    1. The objective of this experiment was to compare how three levels of postbiotic supplementation may attenuate stress, inflammation, and indicators of leaky gut in young horses undergoing an exercise challenge.

2.	Identify response and sources of variation.  
    1.	Treatment factors and levels: One treatment factor (postbiotic supplementation) with 3 levels: 0 mg/kg BW, 46 mg/kg BW, and 92 mg/kg BW. 
    2.	Response: Multiple response factors measured, including serum cortisol, PGE2, SOD, and fecal IgA. Repeated measures over time surrounding the SET (submaximal exercise test): PRE (before exercise), h0 (immediately post), h1, h6 post-exercise.
    3.	Sources of variation: Individual horse, consumption of full amount of supplement, baseline stress/inflammation levels.
    4.	Blocking factor: Sex

3.	Choose a rule for assigning the experimental units to trt (design). 
    1.	We would choose a randomized complete block design.

4.	Specify measurements to be made, experimental procedure, and the anticipated difficulties. 
    1.	Measurements: 
        1. Serum cortisol, PGE2, SOD (measured by commercially available ELISA kit).
        2. Fecal IgA (measured by commercially available ELISA kit).
    2.	Procedure:  30 quarter horse yearlings were be stratified by age, body weight, and sex and assigned to one of three treatment groups: a control, not receiving any postbiotic, a low dose group receiving 46 mg/kg of the postbiotic, and a high dose group receiving 92 mg/kg postbiotic product, which was top-dressed on concentrate fed two times daily. Horses also had ad lib (free-choice) access to water and hay. Horses underwent progressive exercise training for 30 minutes a day, 5 days a week to simulate industry-standard sales preparation protocols. At the end of the study, a submaximal exercise test, or SET, was used to simulate a prolonged intense exercise bout. Horses were balanced by treatment and assigned to one of 4 SET groups which started exercise on 4 consecutive days, with one group per day.
Horses arrived at day - 30 to adapt to the new location. At day - 14, baseline samples were collected and at day - 7, basal diet adaptation began. Day 0 marks initiation of experimental treatments via postbiotic supplementation. Sample collection occured at days -14, 0, 11, 45, and pre- and post-SET. Post-SET samples were taken at 0 h post, 1 hour, 6 hours, and 24 hours post exercise. For the purposes of this project, we will focus on samples surrounding the SET.
To evaluate stress and inflammation, serum samples will be analyzed by ELISA for cortisol, prostaglandin E2 (PGE2), and superoxide dismutase (SOD). Fecal samples will be analyzed by ELISA for fecal IgA. Altogether, these markers allow for evaluation of inflammatory responses to stress events and gut dysfunction. Samples will be numerically coded and processed randomly to prevent any bias from researchers.
    3.	Anticipated difficulties:
        1. Working with animals - Sometimes dangerous to obtain samples, leading to missing observations for some animals. Injuries/lameness can prevent animals from participating in exercise. Animals may not always eat the entirety of their diet, leading to differences in supplement dosing - monitored by collecting and weighing refusals. Individual differences in levels of stress and inflammation in any given animal.
        2. Lab work - Difficulty in troubleshooting and optimizing kits, sample preservation and degradation, human error in lab techniques, environmental conditions in lab.
        3. Equipment - For this particular study, there were issues with the hot walker (how we exercise the horses) that prevented the SET from being as intense as it should have been to illicit a true stress response.

5.	Pilot experiment: 
     1. Will need to run power analysis here..... could use one of the markers I have results on and just run with that for "Pilot Study". Actual power analysis was based off of joint markers for a different manuscript from this study. 

Power test for approximate delta of serum cortisol found to be significantly different in a similar study, SD from current cortisol samples.
Sample Size: `r power.t.test(delta = 20000, sd = 5419.13, sig.level = 0.05, type = "two.sample",
             power = 0.90, alternative = "two.sided")`

6.	Specify the model: 
$Y_{ijht}$ = \mu + \alpha_i + \beta_j + T_h(i) \epsilon_{ijht}$

        Where:

          $Y_{ijt}$ is the response (cortisol, PGE2, SOD, or fecal IgA)

          $\mu$ is a constant

          $\alpha_i$ is main effect of treatment (CON, LOW, HIGH postbiotic supplementation)

          $\beta_j$ is main effect of block (sex)

          $T_{h(i)}$ is random effect of horse within treatment

          $\epsilon_{ijht}$ is the error term

7.	Outline the analysis:
     1. Results will be analyzed using ANOVA for mixed effects models with repeated measures of time.

8.	Calculate number of observations and time/budget. 
     1. 30 horses were used for this study (n = 10 per trt).
     2. The study was completed over a span of 69 days in Fall of 2022.

9.	Review and revise. 


# Part 2: Report

## Introduction
A healthy intestinal barrier helps aid in nutrient absorption and immune defense to pathogens in the gut. When this barrier becomes compromised by things such as illness or stress, pathogens can enter the bloodstream via gaps in cell junctions. This condition is most commonly known as “leaky gut”. This leaky gut can challenge the immune system and lead to weight loss, decreased performance, and other health complications for horses. Dietary supplementation with postbiotics may be used to support proper gut function and overall health, as well as mitigating stress responses. Postbiotics are beneficial byproducts that are created as a result of probiotic activity. Supplementing directly with postbiotics can support normal intestinal barrier integrity and decrease stress responses. Little is known about the response of young horses to supplementation with postbiotics when faced with exercise stress, therefore the objective of this study was to investigate the use of dietary Saccharomyces cerevisiae fermentation product  in mitigating the impacts of training and exercise on intestinal integrity and stress in the young performance horse.

## Experimental units and randomization
Thirty Quarter Horse yearlings (374 ± 25 kg BW; 562 ± 16 d of age; 15 fillies and 15 geldings) were used for this study.
Treatment allocations (n = 10 per treatment) were fixed, while experimental units were assigned random numbers and stratified within treatment groups until optimally balanced groups were created. Horses were stratified by BW, age, and sex and randomly assigned to one of three dietary treatments (n = 10/treatment): CON (0), LOW (46), or HIGH (92 mg/kg BW SCFP).
Blood and fecal samples will be obtained at pre-determined time points surrounding the SET and analyzed by ELISA for biological markers indicating stress and inflammation in response to an exercise challenge.

## Pilot study and sample size calculations
Summarize what you learned from your pilot study. Include sample size calculations - specify and defend your assumptions and choices. It is okay if you cannot achieve the desired sample as long as you justify why.

## Data overview
Describe your data and present figure(s) to illustrate the response.

## Data analysis and results
Describe your statistical methods, check assumptions and interpret your results.

## Discussion
Provide a written discussion about the take-away points from your study. Feel free to include commentary about any lessons you learned through this process.
